### ISSUE TITLE
value regx

### ISSUE THREAD

**Issue by rojanet** [mampfes/esphome_obis_d0#3]
Hallo .

ich benutze ein ir lese kopf an ein esp32 lan modul. 

Zähler ist ein logarex.

und habe ihren code benutz von ihnen.

bekomme auch daten rein. 
nur die volt werden übertragen.

watt un die restlichen daten bekomme ich nichts angezeigt.
Köntten sie mir mal das value regx.

- platform: obis_d0
    name: "Voltage L1"
    obis_d0_id: my_sm
    obis_code: "1-0:32.7.0*255"
    unit_of_measurement: V
    accuracy_decimals: 1
    state_class: measurement
    device_class: voltage
    >>>>   value_regex: "\\d{3}\\.\\d{1}\\*V"   <<<<<

dort bekomme ich die richtigen werte bei den rest nicht.
wie watt ampere.

können sie mir die value rex irgend wie mit teilen oder erklären wie die zusammen gesetzt werden.

gibt es auch ein update intervall jede 1sek. 

Mfg

**Comment by mampfes** [comment]
I created a config file from a "Betriebsanleitung" for LK11/LK13: https://github.com/mampfes/esphome_obis_d0/blob/logarex/doc/logarex.md

Could you please check if all sensors are working properly?

**Comment by rojanet** [comment]
Thanks.

2 Sensoren Zeigen noch falsche werte an.

Sensor 1:

  - platform: obis_d0
    name: "Power Frequency"
    obis_d0_id: my_sm
    obis_code: "1-0:14.7.0*255"
    unit_of_measurement: Hz
    accuracy_decimals: 1
    state_class: measurement
    device_class: frequency
    value_regex: "\\d{2}\\.\\d{1}\\*deg"  <<< Hz umgeändert

   value_regex: "\\d{2}\\.\\d{1}\\*Hz"  

dann geht es.

`[08:07:23][D][obis_d0:185]: OBIS info: 1-0:14.7.0*255 -> 49.9*Hz
[08:07:23][W][obis_d0:017]: value regex doesn't match: 1-0:14.7.0*255 -> 49.9*Hz`


Sensor 2:

`[08:07:23][D][obis_d0:185]: OBIS info: 1-0:0.2.0*255 -> ver.03,432F,20170504
[08:07:23][W][obis_d0:017]: value regex doesn't match: 1-0:0.2.0*255 -> ver.03,432F,20170504`


Ich habe ein LOgarex  LK 13.

super danke .

**Comment by mampfes** [comment]
Great, thanks. I fixed the 2 sensors. Could you please try again?
https://github.com/mampfes/esphome_obis_d0/blob/logarex/doc/logarex.md

**Comment by rojanet** [comment]
translate with Google translater:

Sorry 1 sensor is not working yet.

`[08:04:11][D][obis_d0:185]: OBIS info: 1-0:0.2.0*255 -> ver.03,432F,20170504
[08:04:11][W][obis_d0:017]: value regex doesn't match: 1-0:0.2.0*255 -> ver.03,432F,20170504`

otherwise all good.

The only thing left.
Sometimes I get wrong values.

eg. at Voltage normal value 223.5 V > 600.8 V > 223.6 V which cannot be.
Or e.g. 13,567.3567KWh > 206,678.6788KWh > 13,567.3590KWh.

The peaks disturb.

Values ​​are currently read out with Iobroker and in parallel with HomeAssistant. Because of Dashboard..

Otherwise great work.

German:

Sorry 1 Sensor geht noch nicht.

`[08:04:11][D][obis_d0:185]: OBIS info: 1-0:0.2.0*255 -> ver.03,432F,20170504
[08:04:11][W][obis_d0:017]: value regex doesn't match: 1-0:0.2.0*255 -> ver.03,432F,20170504`

sonst alles gut.

Das einzige was noch ist.
Ab und zu bekomme ich falsche Werte.

Zb. bei Voltage normaler wert 223.5 V > 600,8 V > 223,6 V was nicht sein kann.
Oder zb. 13.567,3567 Kwh > 206.678,6788 Kwh > 13.567,3590 Kwh.

Die peaks stören.

Werte werden im Moment mit Iobroker ausgelesen und parallel mit HomeAssistent. Wegen Dashboard..

Sonst super arbeit.

mfg Ossibayer

**Comment by mampfes** [comment]
Regarding the not working sensor: I didn't find the time yet to really try it out. I assume that the `.` has to be escaped, like this: ` value_regex: "[0-9a-fA-F\\.,]{20}"`. Alternatively you can just allow arbitrary characters `value_regex: ".{20}"` or completely remove the `value_regex`.

Regarding the errorneous values: The problem is that the OBIS D0 protocol doesn't contain any integrity information (except the parity bit) like CRC. Therefore you can't really check the received values. The mitigation I already added is the the `value_regex`. What you can do in addition (as you still get bad values):
1. Try to improve the signal quality by checking the alignment of infrared transmitter (Smart Meter) and receiver (your IR Reader). The have to be eyeball to eyeball.
2. Check if there is an extra IR transmitter LED on your IR reader which is on by default and therefore disturbs the signal. (My IR reader is doing so).
3. In esphome, add a filter to the critical sensors, like quantile or median filter. See: https://esphome.io/components/sensor/index.html#filter-out
